# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c75ab5056aea1396ad1987aab60c59794744ba73ddfdf7582af66d1d087336262d42738bd5a34f1103139880245c73998ad941d3752ef8e928d17cb537fc283d

test:
  secret_key_base: 42be2d85288b878a5eaa67160440b1a1f4999ff69305e443a3547f2c7f431520f113cd978cf53c42ce38890c33e0802ef11515bfc5e2fed633741ac929ab7ed7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
